// 自动生成的曲目数据库
export const SONG_DB = [
  { id: "1_unknown_number", name: "+1(UNKNOWN)-NUMBER", constants: { FTR: 9.7 } },
  { id: "10pt8ion", name: "10pt8ion", constants: { ETR: 10.5, FTR: 9.8 } },
  { id: "1f", name: "1F√", constants: { FTR: 8.2 } },
  { id: "3rd_avenue", name: "3rd Avenue", constants: { FTR: 9.2, PRS: 8.1 } },
  { id: "7thsense", name: "7thSense", constants: { FTR: 9.9 } },
  { id: "8_em", name: "8-EM", constants: { ETR: 10.3, FTR: 9.5 } },
  { id: "99_glooms", name: "99 Glooms", constants: { FTR: 10.3 } },
  { id: "a_wandering_melody_of_love", name: "A Wandering Melody of Love", constants: { FTR: 9.6 } },
  { id: "abstruse_dilemma", name: "Abstruse Dilemma", constants: { FTR: 11.3, PRS: 8.9 } },
  { id: "acheron", name: "Acheron", constants: { FTR: 9.7 } },
  { id: "aegleseeker", name: "Aegleseeker", constants: { FTR: 11.2, PRS: 9.1 } },
  { id: "aether_crest_astral", name: "Aether Crest: Astral", constants: { ETR: 11.5, FTR: 10.6, PRS: 8.9 } },
  { id: "ai_drew", name: "Ai Drew", constants: { FTR: 9.8 } },
  { id: "ai_ue_oon", name: "AI［UE］OON", constants: { FTR: 9.4 } },
  { id: "aleph_0", name: "Aleph-0", constants: { FTR: 10.5, PRS: 8.8 } },
  { id: "alexandrite", name: "Alexandrite", constants: { FTR: 10.0 } },
  { id: "alice_la_mode", name: "Alice à la mode", constants: { FTR: 9.2 } },
  { id: "alice_s_suitcase", name: "Alice's Suitcase", constants: { FTR: 9.1 } },
  { id: "alone_lorn", name: "Alone & Lorn", constants: { FTR: 9.6 } },
  { id: "altair_feat_spila", name: "Altair (feat. *spiLa*)", constants: { FTR: 8.5 } },
  { id: "altale", name: "Altale", constants: { BYD: 10.0, FTR: 9.8 } },
  { id: "alter_ego", name: "ALTER EGO", constants: { ETR: 11.3, FTR: 10.5, PRS: 9.2 } },
  { id: "alterale", name: "AlterAle", constants: { FTR: 9.7 } },
  { id: "altergate", name: "AlterGate", constants: { FTR: 10.7, PRS: 8.7 } },
  { id: "amazing_mightyyyy", name: "AMAZING MIGHTYYYY!!!!", constants: { FTR: 10.7 } },
  { id: "amekagura", name: "Amekagura", constants: { FTR: 9.9 } },
  { id: "amygdata", name: "Amygdata", constants: { FTR: 9.7 } },
  { id: "and_revive_the_melody", name: "And Revive The Melody", constants: { FTR: 10.9, PRS: 8.5 } },
  { id: "andorxor", name: "ANDORXOR", constants: { ETR: 10.8, FTR: 9.9 } },
  { id: "angel_s_boundary", name: "Angel's Boundary", constants: { FTR: 10.2, PRS: 8.5 } },
  { id: "antagonism", name: "Antagonism", constants: { FTR: 9.9 } },
  { id: "antithese", name: "Antithese", constants: { BYD: 9.6, FTR: 8.8 } },
  { id: "an_kumene", name: "Anökumene", constants: { BYD: 9.9, FTR: 9.2 } },
  { id: "april_showers", name: "April showers", constants: { FTR: 8.6 } },
  { id: "arcahv", name: "Arcahv", constants: { FTR: 9.9 } },
  { id: "arcana_eden", name: "Arcana Eden", constants: { BYD: 11.6, FTR: 10.5, PRS: 8.7 } },
  { id: "arghena", name: "Arghena", constants: { FTR: 11.3, PRS: 9.6 } },
  { id: "ascent", name: "Ascent", constants: { FTR: 9.8 } },
  { id: "ashen_6oundary", name: "Ashen 6oundary", constants: { FTR: 9.9 } },
  { id: "astra_walkthrough", name: "Astra walkthrough", constants: { FTR: 9.9 } },
  { id: "astral_quantization", name: "Astral Quantization", constants: { FTR: 10.6, PRS: 8.1 } },
  { id: "astral_tale", name: "Astral tale", constants: { FTR: 9.6 } },
  { id: "astral_exe", name: "Astral.exe", constants: { FTR: 9.5 } },
  { id: "attraqtia", name: "AttraqtiA", constants: { FTR: 10.6, PRS: 8.3 } },
  { id: "aurgelmir", name: "Aurgelmir", constants: { FTR: 10.5, PRS: 8.5 } },
  { id: "auxesia", name: "Auxesia", constants: { FTR: 9.3 } },
  { id: "avant_raze", name: "Avant Raze", constants: { FTR: 9.6 } },
  { id: "awaken_in_ruins", name: "Awaken In Ruins", constants: { FTR: 9.7 } },
  { id: "axium_crisis", name: "Axium Crisis", constants: { BYD: 11.3, FTR: 10.6, PRS: 8.5 } },
  { id: "b_b_k_k_b_k_k", name: "B.B.K.K.B.K.K.", constants: { FTR: 9.7 } },
  { id: "babaroque", name: "Babaroque", constants: { FTR: 8.5 } },
  { id: "back_to_basics", name: "Back to Basics", constants: { FTR: 10.6, PRS: 8.7 } },
  { id: "badtek", name: "BADTEK", constants: { FTR: 9.7 } },
  { id: "bamboo", name: "Bamboo", constants: { FTR: 10.0 } },
  { id: "battle_no_1", name: "BATTLE NO.1", constants: { FTR: 9.7 } },
  { id: "be_there", name: "Be There", constants: { BYD: 10.5, FTR: 9.4 } },
  { id: "beautiful_dreamer", name: "Beautiful Dreamer", constants: { FTR: 9.9 } },
  { id: "beside_you", name: "Beside You", constants: { FTR: 8.7 } },
  { id: "black_lotus", name: "Black Lotus", constants: { FTR: 9.7 } },
  { id: "black_mind", name: "Black MInD", constants: { FTR: 10.8, PRS: 8.0 } },
  { id: "black_mirror_on_the_wall", name: "Black Mirror on the Wall", constants: { ETR: 9.7, FTR: 8.6 } },
  { id: "black_territory", name: "Black Territory", constants: { FTR: 9.8 } },
  { id: "blaster", name: "Blaster", constants: { FTR: 9.3 } },
  { id: "blazing_air", name: "BlazinG AIR", constants: { ETR: 10.1, FTR: 8.9 } },
  { id: "blocked_library", name: "Blocked Library", constants: { FTR: 9.3 } },
  { id: "blrink", name: "BLRINK", constants: { FTR: 9.7 } },
  { id: "blue_comet", name: "Blue comet", constants: { FTR: 8.2 } },
  { id: "blue_rose", name: "Blue Rose", constants: { FTR: 9.1 } },
  { id: "blythe", name: "BlythE", constants: { ETR: 10.5, FTR: 9.4 } },
  { id: "bookmaker_2d_version", name: "Bookmaker (2D Version)", constants: { BYD: 10.0, FTR: 8.3 } },
  { id: "breach_of_faith", name: "Breach of Faith", constants: { BYD: 10.9, FTR: 10.3, PRS: 8.4 } },
  { id: "break_break_break", name: "BREaK! BREaK! BREaK!", constants: { ETR: 10.3, FTR: 8.8 } },
  { id: "buchigire_berserker", name: "BUCHiGiRE Berserker", constants: { FTR: 10.8, PRS: 8.6 } },
  { id: "bullet_waiting_for_me_james_landino_remix", name: "Bullet Waiting for Me (James Landino remix)", constants: { FTR: 8.1 } },
  { id: "call_my_name_feat_yukacco", name: "Call My Name feat. Yukacco", constants: { FTR: 8.7 } },
  { id: "callima_karma", name: "Callima Karma", constants: { FTR: 9.8 } },
  { id: "can_i_friend_you_on_bassbook_lol", name: "Can I Friend You on Bassbook? Lol", constants: { FTR: 9.3 } },
  { id: "capella", name: "Capella", constants: { FTR: 10.2 } },
  { id: "carmine_scythe", name: "Carmine:scythe", constants: { FTR: 9.6 } },
  { id: "chain2nite", name: "CHAIN2NITE", constants: { ETR: 9.9, FTR: 8.6 } },
  { id: "chaos", name: "CHAOS", constants: { FTR: 10.9 } },
  { id: "chaosblast", name: "CHAOSBLAST", constants: { ETR: 10.5, FTR: 9.6 } },
  { id: "chelsea", name: "Chelsea", constants: { FTR: 8.9 } },
  { id: "chromafill", name: "Chromafill", constants: { FTR: 10.0 } },
  { id: "chronicle", name: "Chronicle", constants: { FTR: 10.5, PRS: 8.9 } },
  { id: "chronostasis", name: "Chronostasis", constants: { FTR: 8.9 } },
  { id: "climax", name: "Climax", constants: { FTR: 10.4 } },
  { id: "clotho_and_the_stargazer", name: "Clotho and the stargazer", constants: { ETR: 8.8 } },
  { id: "coastal_highway", name: "Coastal Highway", constants: { FTR: 9.1 } },
  { id: "cocoro_cosmetic", name: "Cocoro*cosmetic", constants: { FTR: 9.2 } },
  { id: "code_oblivion", name: "Code: Oblivion", constants: { ETR: 10.9, FTR: 9.9, PRS: 8.3 } },
  { id: "conflict", name: "Conflict", constants: { FTR: 10.2 } },
  { id: "corps_sans_organes", name: "Corps-sans-organes", constants: { FTR: 10.6 } },
  { id: "corruption", name: "Corruption", constants: { FTR: 9.8 } },
  { id: "cosmica", name: "Cosmica", constants: { FTR: 8.8 } },
  { id: "cosmo_pop_funclub", name: "Cosmo Pop Funclub", constants: { FTR: 8.8 } },
  { id: "crimson_quartz", name: "Crimson Quartz", constants: { ETR: 9.8, FTR: 8.8 } },
  { id: "crimson_throne", name: "Crimson Throne", constants: { FTR: 10.6, PRS: 8.0 } },
  { id: "cross_over", name: "CROSS†OVER", constants: { FTR: 9.4 } },
  { id: "cross_soul", name: "CROSS†SOUL", constants: { FTR: 9.4 } },
  { id: "cry_of_viyella", name: "Cry of viyella", constants: { FTR: 8.7 } },
  { id: "cryogenic", name: "Cryogenic", constants: { ETR: 10.1, FTR: 9.2 } },
  { id: "crystal_gravity", name: "Crystal Gravity", constants: { FTR: 9.4 } },
  { id: "cyaegha", name: "Cyaegha", constants: { FTR: 10.7, PRS: 8.4 } },
  { id: "cyanine", name: "Cyanine", constants: { FTR: 10.6 } },
  { id: "cybernecia_catharsis", name: "Cybernecia Catharsis", constants: { BYD: 9.8, FTR: 9.5 } },
  { id: "cycles", name: "CYCLES", constants: { FTR: 8.8 } },
  { id: "da_at_the_first_seeker_of_souls", name: "DA'AT -The First Seeker of Souls-", constants: { FTR: 10.9, PRS: 8.4 } },
  { id: "dancin_on_a_cat_s_paw", name: "Dancin' on a Cat's Paw", constants: { FTR: 9.2 } },
  { id: "dandelion", name: "Dandelion", constants: { FTR: 8.5 } },
  { id: "dantalion", name: "Dantalion", constants: { FTR: 10.8, PRS: 8.2 } },
  { id: "dataerr0r", name: "DataErr0r", constants: { FTR: 9.5 } },
  { id: "dazzle_hop", name: "Dazzle hop", constants: { FTR: 9.7 } },
  { id: "ddd", name: "DDD", constants: { FTR: 8.5 } },
  { id: "death_by_glamour", name: "Death By Glamour", constants: { ETR: 9.4 } },
  { id: "defection", name: "Defection", constants: { FTR: 9.8 } },
  { id: "dematerialized", name: "Dematerialized", constants: { ETR: 8.3 } },
  { id: "dement_after_legend", name: "Dement ~after legend~", constants: { BYD: 9.9 } },
  { id: "desertrealm", name: "Desertrealm", constants: { FTR: 10.6, PRS: 8.5 } },
  { id: "designant", name: "Designant.", constants: { BYD: 11.9, FTR: 10.9, PRS: 9.6 } },
  { id: "devillic_sphere", name: "Devillic Sphere", constants: { FTR: 9.9 } },
  { id: "dialnote", name: "Dialnote", constants: { FTR: 8.8 } },
  { id: "dies_irae", name: "Dies irae", constants: { ETR: 10.6, FTR: 9.5 } },
  { id: "diode", name: "Diode", constants: { FTR: 8.1 } },
  { id: "disintegration", name: "Disintegration", constants: { ETR: 9.8, FTR: 8.3 } },
  { id: "distorted_fate", name: "Distorted Fate", constants: { ETR: 10.8, FTR: 9.6 } },
  { id: "distortion_human", name: "Distortion Human", constants: { FTR: 9.9 } },
  { id: "divine_light_of_myriad", name: "Divine Light of Myriad", constants: { FTR: 10.8 } },
  { id: "don_t_die", name: "Don't Die", constants: { ETR: 10.1, FTR: 9.4 } },
  { id: "don_t_fight_the_music", name: "Don't Fight The Music", constants: { ETR: 10.7, FTR: 9.3 } },
  { id: "dot_to_dot_feat_shully", name: "Dot to Dot feat. shully", constants: { FTR: 8.3 } },
  { id: "dreadnought", name: "Dreadnought", constants: { FTR: 9.7 } },
  { id: "dreamin_attraction", name: "Dreamin' Attraction!!", constants: { FTR: 9.4 } },
  { id: "drg", name: "DRG", constants: { FTR: 9.4 } },
  { id: "dropdead", name: "Dropdead", constants: { BYD: 10.5, PRS: 9.5, FTR: 9.1 } },
  { id: "dual_dependency", name: "Dual Dependency", constants: { ETR: 10.4, FTR: 9.5 } },
  { id: "dual_doom_deathmatch", name: "Dual Doom Deathmatch", constants: { ETR: 10.3, FTR: 8.9 } },
  { id: "dull_blade", name: "Dull Blade", constants: { FTR: 10.5, PRS: 8.0 } },
  { id: "dx_choseinou_full_metal_shojo", name: "DX Choseinou Full Metal Shojo", constants: { FTR: 9.7 } },
  { id: "dynitik_s", name: "Dynitikós", constants: { FTR: 9.5 } },
  { id: "d_sive", name: "Désive", constants: { ETR: 10.8, FTR: 9.9, PRS: 8.0 } },
  { id: "eccentric_tale", name: "Eccentric Tale", constants: { BYD: 9.9, FTR: 8.4 } },
  { id: "eden", name: "Eden", constants: { FTR: 10.5, PRS: 8.2 } },
  { id: "ego_eimi", name: "Ego Eimi", constants: { FTR: 10.5, PRS: 8.6 } },
  { id: "einherjar_joker", name: "Einherjar Joker", constants: { BYD: 10.9, FTR: 9.8 } },
  { id: "empire_of_winter", name: "Empire of Winter", constants: { FTR: 9.1 } },
  { id: "enchanted_love", name: "Enchanted love", constants: { FTR: 8.6 } },
  { id: "end_of_the_moonlight", name: "End of The Moonlight", constants: { FTR: 9.5 } },
  { id: "energy_synergy_matrix", name: "ENERGY SYNERGY MATRIX", constants: { BYD: 10.3, FTR: 9.6 } },
  { id: "epitaxy", name: "Epitaxy", constants: { ETR: 9.6, FTR: 8.6 } },
  { id: "equilibrium", name: "Equilibrium", constants: { FTR: 9.4 } },
  { id: "essence_of_twilight", name: "Essence of Twilight", constants: { FTR: 9.1 } },
  { id: "eternity", name: "Eternity", constants: { BYD: 9.7 } },
  { id: "eternity_break", name: "Eternity Break", constants: { ETR: 10.4, FTR: 9.6 } },
  { id: "ether_strike", name: "Ether Strike", constants: { FTR: 10.3, PRS: 8.3 } },
  { id: "evening_in_scarlet", name: "Evening in Scarlet", constants: { FTR: 9.5 } },
  { id: "evoltex_poppi_n_mix", name: "Evoltex (poppi'n mix)", constants: { FTR: 8.9 } },
  { id: "extradimensional_cosmic_phenomenon", name: "Extradimensional Cosmic Phenomenon", constants: { ETR: 11.3, FTR: 10.6, PRS: 8.8 } },
  { id: "factorder", name: "Factorder", constants: { ETR: 9.6, FTR: 8.6 } },
  { id: "faint_light_arcaea_edit", name: "Faint Light (Arcaea Edit)", constants: { FTR: 9.1 } },
  { id: "fairytale", name: "Fairytale", constants: { BYD: 9.5 } },
  { id: "fallensquare", name: "Fallensquare", constants: { FTR: 9.7 } },
  { id: "false_embellishment", name: "False Embellishment", constants: { BYD: 9.9, FTR: 9.3 } },
  { id: "fanta5y", name: "FANTA5Y", constants: { FTR: 9.4 } },
  { id: "far_away_light", name: "Far Away Light", constants: { FTR: 9.8 } },
  { id: "feels_so_right_feat_renko", name: "Feels So Right feat. Renko", constants: { FTR: 9.3 } },
  { id: "felis", name: "Felis", constants: { FTR: 10.4 } },
  { id: "felys_final_remix", name: "Felys final remix", constants: { FTR: 9.5 } },
  { id: "filament", name: "Filament", constants: { FTR: 9.7 } },
  { id: "final_step", name: "Final Step!", constants: { FTR: 9.4 } },
  { id: "flashback", name: "Flashback", constants: { FTR: 8.9 } },
  { id: "floating_world", name: "Floating World", constants: { FTR: 9.3 } },
  { id: "fluffy_flash", name: "FLUFFY FLASH", constants: { FTR: 9.8 } },
  { id: "flyburg_and_endroll", name: "Flyburg and Endroll", constants: { FTR: 9.0 } },
  { id: "fracture_ray", name: "Fracture Ray", constants: { FTR: 11.1, PRS: 9.5 } },
  { id: "free_myself", name: "Free Myself", constants: { FTR: 10.0 } },
  { id: "freef4ll", name: "FREEF4LL", constants: { BYD: 9.8, FTR: 8.6 } },
  { id: "furete_mitai", name: "FURETE-MITAI", constants: { ETR: 9.4, FTR: 8.4 } },
  { id: "g_e_n_g_a_o_z_o", name: "G e n g a o z o", constants: { FTR: 10.1, PRS: 8.1 } },
  { id: "galactic_love", name: "Galactic Love", constants: { FTR: 9.0 } },
  { id: "galaxy_friends", name: "Galaxy Friends", constants: { FTR: 9.9 } },
  { id: "garakuta_doll_play", name: "Garakuta Doll Play", constants: { FTR: 10.4 } },
  { id: "gekka_short_version", name: "Gekka (Short Version)", constants: { FTR: 8.6 } },
  { id: "genesis_iris", name: "Genesis (Iris)", constants: { FTR: 8.2 } },
  { id: "genesis_morrigan", name: "Genesis (Morrigan)", constants: { FTR: 9.8 } },
  { id: "genocider", name: "GENOCIDER", constants: { FTR: 10.8, PRS: 8.9 } },
  { id: "gensou_no_satellite", name: "Gensou no Satellite", constants: { ETR: 10.1, FTR: 8.7 } },
  { id: "gimme_caramel_popcorn", name: "Gimme Caramel Popcorn!", constants: { ETR: 9.1, FTR: 8.1 } },
  { id: "gimme_da_blood", name: "GIMME DA BLOOD", constants: { FTR: 10.5 } },
  { id: "gimmick", name: "GIMMICK", constants: { FTR: 9.5 } },
  { id: "give_me_a_nightmare", name: "Give Me a Nightmare", constants: { FTR: 8.9 } },
  { id: "glory_road", name: "GLORY：ROAD", constants: { FTR: 10.5 } },
  { id: "glow", name: "Glow", constants: { FTR: 9.3 } },
  { id: "goldenslaughterer", name: "Goldenslaughterer", constants: { FTR: 9.7 } },
  { id: "good_bye_merry_go_round", name: "Good bye, Merry-Go-Round.", constants: { FTR: 10.6 } },
  { id: "goodrage", name: "GOODRAGE", constants: { ETR: 10.2, FTR: 9.3 } },
  { id: "goodtek_arcaea_edit", name: "GOODTEK (Arcaea Edit)", constants: { BYD: 9.8, FTR: 9.3 } },
  { id: "got_hive_of_ra", name: "Got hive of Ra", constants: { FTR: 9.8 } },
  { id: "grandspell", name: "Grandspell", constants: { FTR: 10.2, PRS: 8.4 } },
  { id: "grievous_lady", name: "Grievous Lady", constants: { FTR: 11.1, PRS: 9.3 } },
  { id: "grimheart", name: "Grimheart", constants: { FTR: 8.7 } },
  { id: "hailstone", name: "Hailstone", constants: { FTR: 9.7 } },
  { id: "halcyon", name: "Halcyon", constants: { FTR: 10.5, PRS: 8.2 } },
  { id: "hall_of_mirrors", name: "Hall of Mirrors", constants: { FTR: 8.2 } },
  { id: "harutopia_utopia_of_spring", name: "Harutopia ~Utopia of Spring~", constants: { FTR: 8.5 } },
  { id: "haze_of_autumn", name: "Haze of Autumn", constants: { FTR: 9.8 } },
  { id: "head_bonk_ache", name: "Head BONK ache", constants: { FTR: 9.4 } },
  { id: "heart", name: "Heart", constants: { FTR: 9.6 } },
  { id: "heart_jackin", name: "Heart Jackin'", constants: { FTR: 9.7 } },
  { id: "heartache", name: "Heartache", constants: { ETR: 8.7 } },
  { id: "heavenly_caress", name: "Heavenly caress", constants: { BYD: 10.9, FTR: 9.8 } },
  { id: "heavensdoor", name: "Heavensdoor", constants: { BYD: 10.8, FTR: 9.9 } },
  { id: "hellohell", name: "HELLOHELL", constants: { ETR: 9.3 } },
  { id: "hidden_rainbows_of_epicurus", name: "Hidden Rainbows of Epicurus", constants: { ETR: 8.8 } },
  { id: "hiiro_gekka_kyoushou_no_zetsu_nayuta_2017_ver", name: "Hiiro Gekka, Kyoushou no Zetsu (nayuta 2017 ver.)", constants: { FTR: 10.3 } },
  { id: "hikari", name: "Hikari", constants: { FTR: 8.1 } },
  { id: "hivemind", name: "HIVEMIND", constants: { FTR: 10.0, PRS: 8.6 } },
  { id: "hotarubi_no_yuki", name: "Hotarubi no Yuki", constants: { FTR: 9.7 } },
  { id: "hybris_the_one_who_shattered", name: "Hybris (The one who shattered)", constants: { FTR: 9.8 } },
  { id: "hyper_vision", name: "HYPER VISION", constants: { FTR: 9.8 } },
  { id: "hypnotize", name: "Hypnotize", constants: { ETR: 9.9, FTR: 8.9 } },
  { id: "i_want_you", name: "I want You", constants: { ETR: 9.4, FTR: 8.3 } },
  { id: "i_ve_heard_it_said", name: "I've heard it said", constants: { FTR: 8.1 } },
  { id: "iconoclast", name: "Iconoclast", constants: { FTR: 9.1 } },
  { id: "ignition", name: "Ignition", constants: { FTR: 9.8 } },
  { id: "ignotus", name: "Ignotus", constants: { BYD: 9.9, FTR: 9.3 } },
  { id: "ikazuchi", name: "Ikazuchi", constants: { FTR: 10.3 } },
  { id: "illegal_paradise", name: "Illegal Paradise", constants: { FTR: 9.5 } },
  { id: "impact", name: "IMPACT", constants: { BYD: 10.4, FTR: 9.6 } },
  { id: "impure_bird", name: "Impure Bird", constants: { FTR: 9.4 } },
  { id: "in_vain", name: "In Vain", constants: { FTR: 9.5 } },
  { id: "incarnator", name: "INCARNATOR₀₀", constants: { ETR: 10.4, FTR: 8.9 } },
  { id: "incomplete_the_one", name: "Incomplete the one", constants: { ETR: 9.9, FTR: 8.8 } },
  { id: "infinite_dimension", name: "INFINITE DIMENSION", constants: { ETR: 10.1, FTR: 8.6 } },
  { id: "infinite_strife", name: "Infinite Strife,", constants: { BYD: 10.9, FTR: 9.9 } },
  { id: "infinity_heaven", name: "Infinity Heaven", constants: { BYD: 9.6 } },
  { id: "init", name: "Init()", constants: { FTR: 9.8 } },
  { id: "inkar_usi", name: "Inkar-usi", constants: { BYD: 9.4 } },
  { id: "innocence", name: "Innocence", constants: { ETR: 9.7, FTR: 8.5 } },
  { id: "internet_overdose", name: "INTERNET OVERDOSE", constants: { FTR: 8.4 } },
  { id: "internet_yamero", name: "INTERNET YAMERO", constants: { FTR: 9.9 } },
  { id: "inverted_world", name: "Inverted World", constants: { ETR: 10.7, FTR: 9.5 } },
  { id: "ionostream", name: "IONOSTREAM", constants: { ETR: 9.7, FTR: 8.7 } },
  { id: "izana", name: "IZANA", constants: { FTR: 10.3, PRS: 8.3 } },
  { id: "jingle", name: "Jingle", constants: { ETR: 9.5 } },
  { id: "journey", name: "Journey", constants: { FTR: 9.1 } },
  { id: "judgement", name: "Judgement", constants: { FTR: 10.5, PRS: 8.6 } },
  { id: "jump", name: "Jump", constants: { FTR: 9.0 } },
  { id: "kanagawa_cyber_culvert", name: "Kanagawa Cyber Culvert", constants: { BYD: 9.8, FTR: 9.0 } },
  { id: "kanbu_de_tomatte_sugu_tokeru", name: "Kanbu de Tomatte Sugu Tokeru", constants: { FTR: 10.1 } },
  { id: "kanjou_no_matenrou_arr_demetori", name: "Kanjou no Matenrou ～Arr.Demetori", constants: { FTR: 9.8 } },
  { id: "kissing_lucifer", name: "Kissing Lucifer", constants: { FTR: 10.4 } },
  { id: "kyoren_romance", name: "KYOREN ROMANCE", constants: { FTR: 10.7 } },
  { id: "la_qryma_of_the_wasteland", name: "La'qryma of the Wasteland", constants: { BYD: 10.0, FTR: 9.1 } },
  { id: "ladymade_star", name: "Ladymade Star", constants: { ETR: 9.2, FTR: 8.4 } },
  { id: "lament_rain", name: "Lament Rain", constants: { BYD: 11.4, FTR: 10.6, PRS: 8.8 } },
  { id: "lamia", name: "LAMIA", constants: { FTR: 11.0, PRS: 8.5 } },
  { id: "lapis", name: "Lapis", constants: { FTR: 9.4 } },
  { id: "last", name: "Last", constants: { FTR: 9.0 } },
  { id: "last_celebration", name: "Last Celebration", constants: { FTR: 10.4 } },
  { id: "last_goodbye", name: "Last Goodbye", constants: { ETR: 9.7, FTR: 8.2 } },
  { id: "lastendconductor", name: "Lastendconductor", constants: { BYD: 10.2, FTR: 9.4 } },
  { id: "lawless_point", name: "Lawless Point", constants: { FTR: 9.0 } },
  { id: "lazy_addiction", name: "Lazy Addiction", constants: { FTR: 9.6 } },
  { id: "leave_all_behind", name: "Leave All Behind", constants: { FTR: 9.2 } },
  { id: "let_you_dive_nitro_rmx", name: "Let you DIVE! (nitro rmx)", constants: { FTR: 9.4 } },
  { id: "let_s_rock_arcaea_mix", name: "Let's Rock (Arcaea mix)", constants: { FTR: 9.7 } },
  { id: "lethaeus", name: "Lethaeus", constants: { FTR: 9.7 } },
  { id: "lethal_voltage", name: "Lethal Voltage", constants: { FTR: 10.4 } },
  { id: "liar", name: "Liar", constants: { FTR: 10.0 } },
  { id: "libertas", name: "Libertas", constants: { BYD: 10.5, FTR: 9.2 } },
  { id: "life_is_piano", name: "Life is PIANO", constants: { FTR: 9.1 } },
  { id: "liftoff", name: "LiftOff", constants: { ETR: 9.8, FTR: 8.2 } },
  { id: "lightning_screw", name: "Lightning Screw", constants: { FTR: 10.5 } },
  { id: "lights_of_muse", name: "Lights of Muse", constants: { FTR: 8.9 } },
  { id: "lilly", name: "Lilly", constants: { ETR: 10.8, FTR: 9.9, PRS: 8.4 } },
  { id: "linear_accelerator", name: "Linear Accelerator", constants: { FTR: 9.8 } },
  { id: "live_fast_die_young", name: "Live Fast Die Young", constants: { FTR: 10.6, PRS: 8.5 } },
  { id: "livht_my_w_y", name: "LIVHT MY WΔY", constants: { FTR: 9.8 } },
  { id: "logos", name: "Logos", constants: { FTR: 10.2 } },
  { id: "lost_civilization", name: "Lost Civilization", constants: { BYD: 9.8, FTR: 9.2 } },
  { id: "lost_desire", name: "Lost Desire", constants: { FTR: 9.8 } },
  { id: "lost_emotion_feat_nomico", name: "Lost Emotion feat. nomico", constants: { FTR: 9.3 } },
  { id: "lost_in_the_abyss", name: "Lost in the Abyss", constants: { FTR: 9.7 } },
  { id: "loveless_dress", name: "Loveless Dress", constants: { FTR: 9.7 } },
  { id: "lucid_traveler", name: "Lucid Traveler", constants: { FTR: 10.5, PRS: 8.9 } },
  { id: "lucifer", name: "Lucifer", constants: { FTR: 8.2 } },
  { id: "lumia", name: "Lumia", constants: { BYD: 9.5, FTR: 8.4 } },
  { id: "luna_rossa", name: "Luna Rossa", constants: { FTR: 9.7 } },
  { id: "lunarorbit_believe_in_the_espebranch_road", name: "LunarOrbit -believe in the Espebranch road-", constants: { FTR: 9.6 } },
  { id: "l_schen", name: "Löschen", constants: { FTR: 10.2 } },
  { id: "macrocosmic_modulation", name: "Macrocosmic Modulation", constants: { FTR: 9.8 } },
  { id: "magnolia", name: "Magnolia", constants: { FTR: 10.2 } },
  { id: "mahoroba", name: "MAHOROBA", constants: { FTR: 9.5 } },
  { id: "malicious_mischance", name: "Malicious Mischance", constants: { FTR: 10.2 } },
  { id: "manic_jeer", name: "Manic Jeer", constants: { FTR: 10.6 } },
  { id: "mantis_arcaea_ultra_bloodrush_vip", name: "MANTIS (Arcaea Ultra-Bloodrush VIP)", constants: { FTR: 9.4 } },
  { id: "marenyx", name: "MARENYX", constants: { ETR: 10.8, FTR: 9.5 } },
  { id: "masquerade_legion", name: "Masquerade Legion", constants: { FTR: 10.0 } },
  { id: "maxrage", name: "MAXRAGE", constants: { FTR: 9.9 } },
  { id: "maze_no_9", name: "Maze No.9", constants: { FTR: 8.9 } },
  { id: "mazy_metroplex", name: "Mazy Metroplex", constants: { FTR: 9.8 } },
  { id: "medusa", name: "Medusa", constants: { FTR: 10.1 } },
  { id: "megalovania", name: "MEGALOVANIA", constants: { ETR: 10.5, FTR: 9.5 } },
  { id: "megalovania_camellia_remix", name: "MEGALOVANIA (Camellia Remix)", constants: { ETR: 10.9, FTR: 9.8, PRS: 8.4 } },
  { id: "melty_rhapsody", name: "Melty Rhapsody", constants: { ETR: 10.4, FTR: 9.6 } },
  { id: "memory_forest", name: "Memory Forest", constants: { FTR: 9.8 } },
  { id: "memoryfactory_lzh", name: "Memoryfactory.lzh", constants: { FTR: 8.9 } },
  { id: "merlin", name: "MERLIN", constants: { BYD: 9.4, FTR: 8.9 } },
  { id: "meta_mysteria", name: "Meta-Mysteria", constants: { FTR: 10.8 } },
  { id: "metallic_punisher", name: "Metallic Punisher", constants: { FTR: 10.3 } },
  { id: "miles", name: "Miles", constants: { ETR: 9.8, FTR: 8.2 } },
  { id: "mirinae", name: "MIRINAE", constants: { FTR: 10.4, PRS: 8.3 } },
  { id: "mirzam", name: "Mirzam", constants: { FTR: 9.9 } },
  { id: "misdeed_la_bont_de_dieu_et_l_origine_du_mal", name: "Misdeed -la bonté de Dieu et l'origine du mal-", constants: { FTR: 10.9, PRS: 8.5 } },
  { id: "mod", name: "Mod", constants: { FTR: 9.4 } },
  { id: "modelista", name: "Modelista", constants: { FTR: 9.9 } },
  { id: "moment", name: "Moment", constants: { BYD: 9.6 } },
  { id: "monochrome_princess", name: "Monochrome Princess", constants: { FTR: 9.7 } },
  { id: "moonheart", name: "Moonheart", constants: { BYD: 9.7, FTR: 8.4 } },
  { id: "morningloom", name: "MORNINGLOOM", constants: { ETR: 9.8, FTR: 8.8 } },
  { id: "mvurbd", name: "MVURBD", constants: { FTR: 10.6 } },
  { id: "my_life_is_mine_alone", name: "My life is mine alone!", constants: { ETR: 10.1, FTR: 8.8 } },
  { id: "nameless_passion", name: "Nameless Passion", constants: { FTR: 9.8 } },
  { id: "neo_wings", name: "NEO WINGS", constants: { FTR: 10.2 } },
  { id: "new_york_back_raise", name: "New York Back Raise", constants: { FTR: 9.9 } },
  { id: "next_to_you", name: "Next to you", constants: { BYD: 9.6, FTR: 8.8 } },
  { id: "nhelv", name: "Nhelv", constants: { BYD: 10.9, FTR: 9.9 } },
  { id: "nightmare", name: "Nightmare", constants: { ETR: 10.8, FTR: 9.8 } },
  { id: "nirv_luce", name: "Nirv lucE", constants: { FTR: 10.2 } },
  { id: "no_way_back", name: "No Way Back", constants: { ETR: 10.4, FTR: 8.9 } },
  { id: "nulctrl", name: "NULCTRL", constants: { FTR: 9.5 } },
  { id: "null_apophenia", name: "NULL APOPHENIA", constants: { FTR: 10.7, PRS: 8.8 } },
  { id: "n_smo", name: "Nέο κόsmo", constants: { FTR: 9.7 } },
  { id: "oblivia", name: "Oblivia", constants: { BYD: 9.7, FTR: 8.3 } },
  { id: "oblivion", name: "OBLIVION", constants: { ETR: 10.1, FTR: 9.5 } },
  { id: "old_school_salvage", name: "Old School Salvage", constants: { FTR: 9.8 } },
  { id: "omajinai", name: "OMAJINAI", constants: { FTR: 9.4 } },
  { id: "omakeno_stroke", name: "OMAKENO Stroke", constants: { BYD: 10.3, FTR: 9.5 } },
  { id: "on_and_on_feat_jenga", name: "On And On!! feat. Jenga", constants: { FTR: 9.5 } },
  { id: "one_last_drive", name: "One Last Drive", constants: { FTR: 8.2 } },
  { id: "one_step_closer", name: "One Step Closer", constants: { FTR: 9.5 } },
  { id: "oracle", name: "Oracle", constants: { FTR: 9.3 } },
  { id: "oshama_scramble", name: "Oshama Scramble!", constants: { FTR: 10.0 } },
  { id: "ouroboros_twin_stroke_of_the_end", name: "Ouroboros -twin stroke of the end-", constants: { FTR: 10.7 } },
  { id: "ouvert_re", name: "Ouvertüre", constants: { FTR: 9.8 } },
  { id: "overwhelm", name: "Overwhelm", constants: { FTR: 10.6, PRS: 8.5 } },
  { id: "paper_witch", name: "Paper Witch", constants: { FTR: 8.7 } },
  { id: "paradox_palette", name: "Paradox Palette", constants: { ETR: 9.9, FTR: 8.8 } },
  { id: "paranoid_arc", name: "Paranoid Arc", constants: { ETR: 10.5, FTR: 9.6 } },
  { id: "particle", name: "Particle", constants: { ETR: 9.7, FTR: 9.5 } },
  { id: "party_vinyl", name: "Party Vinyl", constants: { BYD: 10.3, FTR: 9.4 } },
  { id: "pentiment", name: "Pentiment", constants: { BYD: 11.5, FTR: 10.4, PRS: 8.7 } },
  { id: "phantasia", name: "Phantasia", constants: { FTR: 9.2 } },
  { id: "pico_pico_translation", name: "PICO-Pico-Translation!", constants: { FTR: 9.4 } },
  { id: "placebo_battler", name: "Placebo♥Battler", constants: { FTR: 10.4, PRS: 8.3 } },
  { id: "pragmatism", name: "PRAGMATISM", constants: { BYD: 11.2, FTR: 10.1, PRS: 8.6 } },
  { id: "prayer", name: "Prayer", constants: { ETR: 9.1, FTR: 8.2 } },
  { id: "primeval_texture", name: "Primeval Texture", constants: { FTR: 9.0 } },
  { id: "primitive_lights", name: "PRIMITIVE LIGHTS", constants: { FTR: 10.8, PRS: 8.8 } },
  { id: "prism", name: "Prism", constants: { FTR: 8.0 } },
  { id: "protoflicker", name: "Protoflicker", constants: { FTR: 9.8 } },
  { id: "pupa", name: "PUPA", constants: { FTR: 10.4 } },
  { id: "purgatorium", name: "Purgatorium", constants: { BYD: 9.6, FTR: 8.4 } },
  { id: "purple_verse", name: "Purple Verse", constants: { BYD: 10.6, FTR: 9.6 } },
  { id: "qovat", name: "Qovat", constants: { FTR: 10.4, PRS: 8.2 } },
  { id: "qualia_ideaesthesia", name: "Qualia -ideaesthesia-", constants: { BYD: 9.8, FTR: 9.1 } },
  { id: "quon_dj_noriken", name: "Quon (DJ Noriken)", constants: { BYD: 10.2, FTR: 8.7 } },
  { id: "quon_feryquitous", name: "Quon (Feryquitous)", constants: { FTR: 9.6 } },
  { id: "rabbit_in_the_black_room", name: "Rabbit In The Black Room", constants: { FTR: 8.4 } },
  { id: "rain_of_conflict_in_a_radiant_abyss", name: "Rain of Conflict in a Radiant Abyss", constants: { ETR: 10.5, FTR: 9.5 } },
  { id: "raven_s_pride", name: "Raven's Pride", constants: { FTR: 9.4 } },
  { id: "rays_of_remnant", name: "Rays of Remnant", constants: { BYD: 10.4, FTR: 9.7 } },
  { id: "reconstruction", name: "REconstruction", constants: { FTR: 8.4 } },
  { id: "red_and_blue", name: "Red and Blue", constants: { BYD: 10.2, FTR: 9.4 } },
  { id: "redolent_shape", name: "Redolent Shape", constants: { FTR: 10.2 } },
  { id: "redraw_the_colorless_world", name: "Redraw the Colorless World", constants: { FTR: 9.4 } },
  { id: "reinvent", name: "Reinvent", constants: { FTR: 8.5 } },
  { id: "rekka_resonance", name: "REKKA RESONANCE", constants: { FTR: 10.7, PRS: 8.9 } },
  { id: "relentless", name: "Relentless", constants: { FTR: 8.0 } },
  { id: "remind_the_souls_short_version", name: "Remind the Souls (Short Version)", constants: { FTR: 9.6 } },
  { id: "renegade", name: "Renegade", constants: { BYD: 10.2, FTR: 9.6 } },
  { id: "revixy", name: "ReviXy", constants: { FTR: 9.1 } },
  { id: "rgb", name: "RGB", constants: { FTR: 9.8 } },
  { id: "ringed_genesis", name: "Ringed Genesis", constants: { FTR: 10.8, PRS: 8.4 } },
  { id: "rise_of_the_world", name: "Rise of the World", constants: { FTR: 10.5, PRS: 8.1 } },
  { id: "rost_page_gene", name: "ROST PAGE GENE", constants: { FTR: 10.3, PRS: 8.2 } },
  { id: "rugie", name: "Rugie", constants: { FTR: 9.2 } },
  { id: "sacrifice_feat_ayame", name: "SACRIFICE feat. ayame", constants: { FTR: 9.7 } },
  { id: "saikyo_stronger", name: "SAIKYO STRONGER", constants: { FTR: 11.0, PRS: 9.4 } },
  { id: "saint_or_sinner", name: "Saint or Sinner", constants: { BYD: 10.4, FTR: 8.8 } },
  { id: "sakura_fubuki", name: "Sakura Fubuki", constants: { FTR: 9.4 } },
  { id: "san_skia", name: "San skia", constants: { FTR: 8.3 } },
  { id: "satisfaction", name: "SATISFACTION", constants: { ETR: 9.5, FTR: 8.5 } },
  { id: "sayonara_hatsukoi", name: "Sayonara Hatsukoi", constants: { ETR: 8.5 } },
  { id: "scarlet_cage", name: "Scarlet Cage", constants: { FTR: 9.8 } },
  { id: "scarlet_lance", name: "Scarlet Lance", constants: { FTR: 10.0 } },
  { id: "scarlet_lunar_empress", name: "Scarlet Lunar Empress", constants: { FTR: 9.8 } },
  { id: "seclusion", name: "Seclusion", constants: { FTR: 10.6 } },
  { id: "see_the_lights", name: "See the Lights!", constants: { ETR: 9.6, FTR: 8.6 } },
  { id: "senkyou", name: "Senkyou", constants: { FTR: 8.7 } },
  { id: "shades_of_light_in_a_transcendent_realm", name: "Shades of Light in a Transcendent Realm", constants: { BYD: 9.1, FTR: 8.3 } },
  { id: "sheriruth", name: "Sheriruth", constants: { FTR: 10.0 } },
  { id: "sheriruth_laur_remix", name: "Sheriruth (Laur Remix)", constants: { FTR: 10.5 } },
  { id: "shinchoku_doudesuka", name: "Shinchoku Doudesuka?", constants: { ETR: 9.9, FTR: 8.8 } },
  { id: "shrink", name: "Shrink", constants: { FTR: 9.8 } },
  { id: "sign_of_10_5km", name: "Sign of \"10.5km\"", constants: { FTR: 9.2 } },
  { id: "signal", name: "Signal", constants: { ETR: 10.7, FTR: 9.8 } },
  { id: "silent_rush", name: "Silent Rush", constants: { FTR: 8.6 } },
  { id: "singularity", name: "Singularity", constants: { FTR: 10.5, BYD: 10.4 } },
  { id: "small_cloud_sugar_candy", name: "Small Cloud Sugar Candy", constants: { BYD: 10.3, FTR: 9.3 } },
  { id: "snow_white", name: "Snow White", constants: { BYD: 9.7, FTR: 8.4 } },
  { id: "solitary_dream", name: "Solitary Dream", constants: { FTR: 8.8 } },
  { id: "someday", name: "Someday", constants: { FTR: 9.5 } },
  { id: "soundwitch", name: "SOUNDWiTCH", constants: { FTR: 9.8 } },
  { id: "specta", name: "Specta", constants: { FTR: 9.4 } },
  { id: "spider_s_thread", name: "Spider's Thread", constants: { FTR: 10.8 } },
  { id: "spirit_of_the_dauntless", name: "Spirit of the Dauntless", constants: { FTR: 10.5 } },
  { id: "stager_all_stage_clear", name: "STAGER (ALL STAGE CLEAR)", constants: { FTR: 9.5 } },
  { id: "stargate_extreme", name: "STARGATE EXTREME", constants: { ETR: 9.9, FTR: 9.3 } },
  { id: "stasis", name: "Stasis", constants: { FTR: 10.8 } },
  { id: "straight_into_the_lights", name: "Straight into the lights", constants: { ETR: 10.5, FTR: 9.5 } },
  { id: "stratoliner", name: "Stratoliner", constants: { FTR: 9.6 } },
  { id: "strongholds", name: "Strongholds", constants: { FTR: 9.2 } },
  { id: "subsphere_in_eclosion", name: "Subsphere in Eclosion", constants: { ETR: 10.6, FTR: 9.6, PRS: 8.1 } },
  { id: "sulfur", name: "Sulfur", constants: { FTR: 9.7 } },
  { id: "summer_fireworks_of_love", name: "Summer Fireworks of Love", constants: { FTR: 9.9 } },
  { id: "suomi", name: "Suomi", constants: { ETR: 8.9 } },
  { id: "super_ambulance", name: "SUPER AMBULANCE", constants: { FTR: 10.3 } },
  { id: "supernova", name: "SUPERNOVA", constants: { FTR: 9.7 } },
  { id: "surrender", name: "Surrender", constants: { FTR: 8.8 } },
  { id: "swan_song", name: "Swan Song", constants: { FTR: 9.9 } },
  { id: "syriana", name: "Syriana", constants: { FTR: 9.9 } },
  { id: "syro", name: "Syro", constants: { FTR: 9.3 } },
  { id: "sy_ten", name: "Syūten", constants: { FTR: 8.5 } },
  { id: "taboo_tears_you_up_2017", name: "Taboo tears you up 2017", constants: { ETR: 9.8, FTR: 8.4 } },
  { id: "technicolour", name: "Technicolour", constants: { FTR: 9.8 } },
  { id: "tempestissimo", name: "Tempestissimo", constants: { BYD: 11.7, FTR: 10.7, PRS: 9.5 } },
  { id: "temptation", name: "TEmPTaTiON", constants: { FTR: 10.9, PRS: 8.2 } },
  { id: "teravolt", name: "TeraVolt", constants: { FTR: 10.8, PRS: 8.9 } },
  { id: "teriqma", name: "Teriqma", constants: { BYD: 9.7, FTR: 9.4 } },
  { id: "testify", name: "Testify", constants: { BYD: 12.0, FTR: 10.9, PRS: 9.4 } },
  { id: "the_raft_taught_me_your_heart_will_always_find_a_way", name: "The 'Raft' taught me: your heart will always find a way.", constants: { ETR: 10.4, FTR: 9.5 } },
  { id: "the_forgotten_forest_haven", name: "The Forgotten Forest Haven", constants: { FTR: 9.7 } },
  { id: "the_formula", name: "The Formula", constants: { FTR: 9.3 } },
  { id: "the_message", name: "The Message", constants: { FTR: 9.7 } },
  { id: "the_survivor_game_edit", name: "The Survivor (Game Edit)", constants: { FTR: 9.9 } },
  { id: "the_ultimacy", name: "THE ULTIMACY", constants: { FTR: 9.8 } },
  { id: "third_sun", name: "Third Sun", constants: { ETR: 10.0, FTR: 9.4 } },
  { id: "tic_tac_toe", name: "Tic! Tac! Toe!", constants: { ETR: 9.9, FTR: 8.8 } },
  { id: "tie_me_down_gently", name: "Tie me down gently", constants: { FTR: 8.3 } },
  { id: "tiferet", name: "Tiferet", constants: { FTR: 10.3 } },
  { id: "to_the_furthest_dream", name: "To the Furthest Dream", constants: { FTR: 9.8, PRS: 8.5 } },
  { id: "to_the_milky_way", name: "To the Milky Way", constants: { FTR: 10.4, PRS: 8.9 } },
  { id: "to_alice_liddell", name: "To: Alice Liddell", constants: { FTR: 10.3 } },
  { id: "transient_space", name: "Transient Space", constants: { FTR: 9.5 } },
  { id: "trap_crow", name: "Trap Crow", constants: { FTR: 9.9 } },
  { id: "trappola_bewitching", name: "Trappola bewitching", constants: { BYD: 10.6, FTR: 9.9 } },
  { id: "trpno", name: "TRPNO", constants: { FTR: 10.0 } },
  { id: "trrricksters", name: "Trrricksters!!", constants: { FTR: 10.1 } },
  { id: "tsuki_ni_murakumo_hana_ni_kaze", name: "Tsuki ni Murakumo, Hana ni Kaze", constants: { FTR: 8.7 } },
  { id: "turbocharger", name: "Turbocharger", constants: { FTR: 9.0 } },
  { id: "twilight_concerto", name: "Twilight Concerto", constants: { ETR: 10.5, FTR: 9.5 } },
  { id: "u_a_d", name: "U.A.D", constants: { ETR: 9.8, FTR: 8.7 } },
  { id: "ultimate_taste", name: "Ultimate taste", constants: { FTR: 9.9 } },
  { id: "ultradiaxon_n3", name: "Ultradiaxon-N3", constants: { FTR: 10.3, PRS: 8.5 } },
  { id: "undefined", name: "Undefined", constants: { FTR: 9.4 } },
  { id: "undying_macula", name: "Undying Macula", constants: { ETR: 11.0, FTR: 10.1, PRS: 8.7 } },
  { id: "unknown_levels", name: "UNKNOWN LEVELS", constants: { FTR: 10.6, PRS: 8.1 } },
  { id: "used_to_be", name: "Used to be", constants: { FTR: 9.2 } },
  { id: "vainspire", name: "Vainspire", constants: { ETR: 9.9, FTR: 8.4 } },
  { id: "valhalla_0", name: "Valhalla:0", constants: { FTR: 10.2 } },
  { id: "vallista", name: "Vallista", constants: { FTR: 9.7 } },
  { id: "vandalism", name: "Vandalism", constants: { FTR: 9.7 } },
  { id: "vecto", name: "VECTOЯ", constants: { FTR: 9.4 } },
  { id: "vexaria", name: "Vexaria", constants: { BYD: 9.0 } },
  { id: "vicious_heroism", name: "Vicious Heroism", constants: { BYD: 11.2, FTR: 10.0 } },
  { id: "vindication", name: "Vindication", constants: { FTR: 9.6 } },
  { id: "viola_illyria", name: "Viola Illyria", constants: { FTR: 9.5 } },
  { id: "virtus", name: "ViRTUS", constants: { ETR: 10.9, FTR: 9.9, PRS: 8.6 } },
  { id: "vivid_theory", name: "Vivid Theory", constants: { FTR: 8.8 } },
  { id: "viyella_s_tears", name: "Viyella's Tears", constants: { FTR: 10.3 } },
  { id: "vulc_nus", name: "Vulcānus", constants: { FTR: 10.9, PRS: 8.5 } },
  { id: "wait_for_dawn", name: "WAIT FOR DAWN", constants: { FTR: 8.7 } },
  { id: "wake_in_hour", name: "Wake in Hour", constants: { ETR: 8.7 } },
  { id: "waltz_for_lorelei", name: "Waltz for Lorelei", constants: { ETR: 9.8, FTR: 8.8 } },
  { id: "we_re_all_gonna_die", name: "We're All Gonna Die", constants: { ETR: 10.9, FTR: 10.1, PRS: 8.0 } },
  { id: "welcome_queen_of_fiction", name: "Welcome, Queen of Fiction.", constants: { ETR: 10.9, FTR: 10.1, PRS: 8.5 } },
  { id: "wish_upon_a_snow", name: "Wish Upon a Snow", constants: { FTR: 10.5 } },
  { id: "with_u", name: "With U", constants: { FTR: 9.4 } },
  { id: "won_t_back_down", name: "Won't Back Down", constants: { FTR: 9.8 } },
  { id: "world_ender", name: "World Ender", constants: { BYD: 11.1, FTR: 10.0 } },
  { id: "world_fragments_iii_radio_edit", name: "World Fragments III(radio edit)", constants: { FTR: 9.8 } },
  { id: "world_vanquisher", name: "World Vanquisher", constants: { FTR: 10.7 } },
  { id: "world_execute_me", name: "World.execute(me);", constants: { FTR: 8.0 } },
  { id: "xanatos", name: "Xanatos", constants: { FTR: 10.0 } },
  { id: "xeraphinite", name: "Xeraphinite", constants: { FTR: 9.8 } },
  { id: "xterfusion", name: "Xterfusion", constants: { ETR: 10.7, FTR: 9.8, PRS: 8.3 } },
  { id: "xtreme", name: "XTREME", constants: { FTR: 10.5 } },
  { id: "xxium_and_purple_haze", name: "Xxium and Purple haze", constants: { ETR: 10.5, FTR: 9.9 } },
  { id: "yomibito_shirazu", name: "Yomibito shirazu", constants: { FTR: 9.8, PRS: 8.0 } },
  { id: "yosakura_fubuki", name: "Yosakura Fubuki", constants: { FTR: 9.4 } },
  { id: "your_best_nightmare", name: "Your Best Nightmare", constants: { BYD: 10.2, FTR: 8.9 } },
  { id: "your_voice_so_feat_such", name: "Your voice so... feat. Such", constants: { FTR: 9.4 } },
  { id: "zephyrlasting", name: "Zephyrlasting", constants: { ETR: 10.3, FTR: 9.5 } },
  { id: "song_7565639739358350424", name: "~ +", constants: { FTR: 9.9, PRS: 8.0 } },
  { id: "vril_flicka_i_krans", name: "Ävril -Flicka i krans-", constants: { FTR: 8.3 } },
  { id: "song_5872086568015209589", name: "͟͝͞Ⅱ́̕", constants: { FTR: 10.8, PRS: 8.9 } },
  { id: "terl_us", name: "Αterlβus", constants: { FTR: 10.2 } },
  { id: "uar_ina", name: "Γuarδina", constants: { FTR: 10.4, PRS: 8.0 } },
  { id: "z_le", name: "ΛZΛLEΛ", constants: { ETR: 10.0, FTR: 9.4 } },
  { id: "song_7269322465703689125", name: "Μ", constants: { FTR: 9.7 } },
  { id: "song_2641845511030743638", name: "ΟΔΥΣΣΕΙΑ", constants: { FTR: 9.5 } },
  { id: "tau", name: "Τ (tau)", constants: { FTR: 9.7 } },
  { id: "4", name: "Ω4", constants: { FTR: 10.8 } },
  { id: "song_8283574980899415617", name: "〇、", constants: { FTR: 9.5 } },
  { id: "1f1e33", name: "＃1f1e33", constants: { FTR: 11.1, PRS: 9.2 } },
  { id: "x", name: "［X］", constants: { FTR: 10.6 } },
];
